### ISSUE TITLE
Canonical domain

### ISSUE THREAD

**Issue by dgw** [YOURLS/docs#43]
I can visit yourls-docs.pages.dev without being redirected to the canonical domain, docs.yourls.org.

This is apparently useful _to me_ right now, since there is some issue with DNS resolution on my LAN or ISP that makes docs.yourls.org fail to resolve, but for most people (and SEO) it would be better to direct people to the canonical domain.

**Comment by ozh** [comment]
For users, I have no firm opinion. I mean, if docs.yourls.org doesn't work for some reason, and if the user happens to know about the pages.dev subdomain (who does ??), well, good for them after all ?

From an SEO pov, adding a header tag with canonical URL on each page would be enough I think. But I don't know how to do it :)

**Comment by dgw** [comment]
About actually adding it, I figured @LeoColomb would take care of that with [CF Pages' redirect feature](https://developers.cloudflare.com/pages/platform/redirects/). 🙂

**Comment by LeoColomb** [comment]
Well, as mentioned by @ozh, nobody know about the page.dev domain.
Probably as much as you didn't know that `https://vuejs.org/` got its alternative `https://main--vuejs.netlify.app/`.
So 🤷‍♂️

From SEO perspective, the site's manifest is probably doing a great job, plus meta enforcing it in case of sharing.
And let's be honest, SEO optimisation is not the goal. Home site (yourls.org) should be much more focused on that.

Third point, these platforms (or at least the biggest Cloudflare and Netlify) don't support domain redirections because of their infra. See the support table on the doc page you linked. 🤓

![image](https://user-images.githubusercontent.com/846943/168497039-47c33cf5-7ec2-4870-93e4-485d1ef9711e.png)

**Comment by dgw** [comment]
Netlify most certainly does support domain redirection (try sopel.netlify.com 😉). Cloudflare is behind the curve on its redirection support, I guess.

If it's technically impossible to set up this redirect right now, the only question remaining is: Would you set it up if it _was_ possible? If not, close the issue. If you would, leave it open in hopes that CF adds the required feature. ☺

**Comment by LeoColomb** [comment]
> Netlify most certainly does support domain redirection

Indeed!
That said, [seing their big warning](https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects), not sure they allow internal `netlify.app` redirection tbh...

> Would you set it up if it _was_ possible?

I don't think so, the less we add code & config customizations, the happier I'll be (the lower the maintenance cost).
If it becomes an problem, we can still do it later.

**Comment by dgw** [comment]
> > Would you set it up if it _was_ possible?
> 
> I don't think so

Then let's close out this idea issue. :)

**Comment by LeoColomb** [comment]
For your information, I'm glad to share this has been fixed, @dgw. ✨😎
